### ISSUE TITLE
Feature Change: Organize role counts displayed by Stats command 

### ISSUE THREAD

**Issue by aMahanna** [ieee-uottawa/SITE-Bot#19]
🥴 
<img src="https://user-images.githubusercontent.com/43019056/104871489-2bdeac80-5919-11eb-8bc8-39b9569f2291.png"  width="400"/>

The Role Counts (I.e all stats under `Bot Count`) should be organized into the following: 
* year
* program
* association / student society
* pronoun
* miscellaneous

**Comment by photonized** [comment]
Can you add a counter for people that don't have any role at all?

**Comment by aMahanna** [comment]
> Can you add a counter for people that don't have any role at all?

yeah for sure let me look into it
