### ISSUE TITLE
Fix: Multiple exclamation marks picked up by bot

### ISSUE THREAD

**Issue by aMahanna** [ieee-uottawa/SITE-Bot#48]
## Use case 
<img src="https://user-images.githubusercontent.com/43019056/112413741-1a3dca80-8cf7-11eb-8f4d-f0a5a01cd743.png"  width="500"/>

## Result
<img src="https://user-images.githubusercontent.com/43019056/112414888-3b071f80-8cf9-11eb-90bf-845fb643c627.png"  width="800"/>

**Comment by RyanFleck** [comment]
https://github.com/ieee-uottawa/SITE-Bot/pull/50 resolved
