### ISSUE TITLE
Feature Request: Stock Price Command

### ISSUE THREAD

**Issue by RyanFleck** [ieee-uottawa/SITE-Bot#8]
`!stonk`

**Comment by aMahanna** [comment]
I can take a look at this, I've done something similar before

**Comment by aMahanna** [comment]
Regarding the stock API, I'll start with using the [Financial Modelling Prep](https://financialmodelingprep.com/developer) one for now. It's the only one I've used so far, but if you have any other ones in mind I would be happy to switch it. For now this is the free plan that they offer: 

![image](https://user-images.githubusercontent.com/43019056/104758903-16a52a80-572d-11eb-841f-a18f29dc16fc.png)

**Comment by aMahanna** [comment]
Hmm actually now that I think about it the Yahoo Finance API allows 500 calls in its free tier. Might switch to that...

**Comment by RyanFleck** [comment]
Well, both are good options, but the higher volume does give us more headroom.

Make sure you `.catch()` the calls to the service and send an apology to the user if we do hit that rate limit :)
