### ISSUE TITLE
Requesting help in a DM prints both messages.

### ISSUE THREAD

**Issue by RyanFleck** [ieee-uottawa/SITE-Bot#9]
When requested as a direct message, `!help` and `!contribute` should probably print just the full manual.

![image](https://user-images.githubusercontent.com/28709508/104754545-5bc65e00-5727-11eb-9f0e-7803d92c4ded.png)

**Comment by aMahanna** [comment]
Ah, I can take a look, probably just a matter of adding a check to see if the command request has been sent in a channel  or a DM.
